In [2]:
#Lesson 1 INTRO - Using lista
import statistics as stat
x=[60,70,8,90,78]
mn=stat.mean(x)
md=stat.mode(x)
mdn=stat.median(x)
std=stat.stdev(x)
var=stat.variance(x)
print('Summary statistics is as follows')
print(f'The mean is: {mn:.3f}')
print(f'The mode is is: {md:.2f}')
print(f'The median is: {mdn:.2f}')
print(f'The standard deviation is: {std:.2f}')
print(f'The variance is: {var:.2f}')

Summary statistics is as follows
The mean is: 61.200
The mode is is: 60.00
The median is: 70.00
The standard deviation is: 31.70
The variance is: 1005.20

In [3]:
#Lesson 2 NUMPY: using arrays
import numpy as np
x=[50,60,80,80,50]
arr=np.array(x)#using array function to convert list to array
arr_mean=np.mean(arr)
arr_stdev=np.std(arr)
arr_dim=arr.ndim
arr_shape=arr.shape
print(f'The mean is: {arr_mean}')
print(f'The standard deviation is: {arr_stdev}')
print(f"The dimension of the array is: {arr_dim}")
print(f"The shape of the array is: {arr_shape}")

The mean is: 64.0
The standard deviation is: 13.564659966250536
The dimension of the array is: 1
The shape of the array is: (5,)

In [9]:
import numpy as np
exams=[[50,60,70,80],
       [54,65,47,32],
       [47,32,45,78]]
exam_array=np.array(exams)
exam_size=exam_array.size
exam_dim=exam_array.ndim
exam_shape=exam_array.shape
exam_type=exam_array.dtype
exam_itemSize=exam_array.itemsize
print(exams)
print(f"The size of the array is: {exam_size}")
print(f"The dimension of the array is: {exam_dim}")
print(f"The shape of the array is: {exam_shape}")
print(f"The type of the array is: {exam_type}")
print(f"The item size of the array is: {exam_itemSize}")

[[50, 60, 70, 80], [54, 65, 47, 32], [47, 32, 45, 78]]
The size of the array is: 12
The dimension of the array is: 2
The shape of the array is: (3, 4)
The type of the array is: int32
The item size of the array is: 4

In [11]:
import numpy as np 
exams=[[[40,50,60],
   [50,70,90]],
   [[40,50,60],
   [50,70,90]],
   [[40,50,60],
   [50,70,90]]]
exam_array=np.array(exams)
exam_size=exam_array.size
exam_dim=exam_array.ndim
exam_shape=exam_array.shape
exam_type=exam_array.dtype
exam_itemSize=exam_array.itemsize
print(exams)
print(f"The size of the array is: {exam_size}")
print(f"The dimension of the array is: {exam_dim}")
print(f"The shape of the array is: {exam_shape}")
print(f"The type of the array is: {exam_type}")
print(f"The item size of the array is: {exam_itemSize}")

[[[40, 50, 60], [50, 70, 90]], [[40, 50, 60], [50, 70, 90]], [[40, 50, 60], [50, 70, 90]]]
The size of the array is: 18
The dimension of the array is: 3
The shape of the array is: (3, 2, 3)
The type of the array is: int32
The item size of the array is: 4

In [2]:
#INDEXING
import numpy as np
arr_list=[[1,2,3],[4,6,7]]
arry_data=np.array(arr_list)
print(arry_data[1,1])

6

In [7]:
#INDEXING
arr=np.array([[[10,20,30],[40,60,70]],[[21,22,33],[44,55,56 ]]])
print(arr)
print(arr[1,1,2])
print(arr[-1,-1,-1])

[[[10 20 30]
  [40 60 70]]

 [[21 22 33]
  [44 55 56]]]
56
56

In [9]:
arr=np.array([[40,50,60],
              [44,55,56],
              [41,42,43],
              [44,65,66],
             [91,52,53],
             [48,52,86]])
total=np.sum(arr,axis=0)
mn=np.mean(arr,axis=0)
st=np.std(arr,axis=0)
print(total)
print(f'{mn}')
print(st)

[308 316 364]
[51.33333333 52.66666667 60.66666667]
[17.92267341  6.82316316 13.3124837 ]

In [2]:
#arithmetic operations 24/03/2026
#add
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the + operator
result1 = first_array+second_array
print("Using the + operator:", result1)
#using the add() function
result2 = np.add(first_array,second_array)
print("Using the add() function:", result2)

Using the + operator: [ 3  7 11 15]
Using the add() function: [ 3  7 11 15]

In [9]:
#subtract
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the - operator
result1 = first_array-second_array
print("Using the - operator:", result1)
#using the subtract function
result2 = np.subtract(first_array,second_array)
print("Using the subtract() function:", result2)

Using the - operator: [-1 -1 -1 -1]
Using the subtract() function: [-1 -1 -1 -1]

In [ ]:
#multiply
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the * operator
result1 = first_array*second_array
print("Using the * operator:", result1)
#using the multiply() function
result2 = np.multiply(first_array,second_array)
print("Using the multiply() function:", result2)

In [ ]:
#division
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the / operator
result1 = first_array+second_array
print("Using the + operator:", result1)
#using the add() function
result2 = np.add(first_array,second_array)
print("Using the add() function:", result2)

In [ ]:
#add
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the - operator
result1 = first_array+second_array
print("Using the + operator:", result1)
#using the add() function
result2 = np.add(first_array,second_array)
print("Using the add() function:", result2)

In [ ]:
#add
import numpy as np
arr1=[1,3,5,7]
arr2=[2,4,6,8]
first_array=np.array(arr1)
second_array=np.array(arr2)
#using the - operator
result1 = first_array+second_array
print("Using the + operator:", result1)
#using the add() function
result2 = np.add(first_array,second_array)
print("Using the add() function:", result2)

In [4]:
exam_mark=[[50,60,70,80,90],
           [55,65,75,85,95],
           [41,52,63,74,78],
           [78,45,63,47,78],
           [47,56,78,63,87]]
marks=np.array(exam_mark)
marks

array([[50, 60, 70, 80, 90],
       [55, 65, 75, 85, 95],
       [41, 52, 63, 74, 78],
       [78, 45, 63, 47, 78],
       [47, 56, 78, 63, 87]])

In [5]:
#maximum
max_value=np.max(marks,axis=0)
max_value

array([78, 65, 78, 85, 95])

In [6]:
#minimum
min_value=np.min(marks,axis=0)
min_value

array([41, 45, 63, 47, 78])

In [14]:
#mean vertically/column-wise/0 axis
mean_value_vertical=np.mean(marks,axis=0)
mean_value_vertical

array([54.2, 55.6, 69.8, 69.8, 85.6])

In [13]:
#mean vertically/column-wise/0 axis
mean_value_vertical=np.mean(marks,axis=0)
mean_value_vertical
#Reshaping the mean_value_vertical array to a 2D so as to concatenate
mean_value_vertical.reshape(1,5)

array([[54.2, 55.6, 69.8, 69.8, 85.6]])

In [18]:
mean_value_vertical_concat=np.concatenate((marks,mean_value_vertical.reshape(1,5)),axis=0)
mean_value_vertical_concat

array([[50. , 60. , 70. , 80. , 90. ],
       [55. , 65. , 75. , 85. , 95. ],
       [41. , 52. , 63. , 74. , 78. ],
       [78. , 45. , 63. , 47. , 78. ],
       [47. , 56. , 78. , 63. , 87. ],
       [54.2, 55.6, 69.8, 69.8, 85.6]])

In [12]:
#USING V-STACK
mean_value_vertical_stack=np.vstack((marks,mean_value_vertical.reshape(1,5)))
mean_value_vertical_stack

array([[50. , 60. , 70. , 80. , 90. ],
       [55. , 65. , 75. , 85. , 95. ],
       [41. , 52. , 63. , 74. , 78. ],
       [78. , 45. , 63. , 47. , 78. ],
       [47. , 56. , 78. , 63. , 87. ],
       [54.2, 55.6, 69.8, 69.8, 85.6]])

In [11]:
std_value_vertical = np.std(marks,axis=0)
std_value_vertical
std_value_vertical_stack = np.vstack((mean_value_vertical_stack,std_value_vertical.reshape(1,5)))
std_value_vertical_stack

array([[50.        , 60.        , 70.        , 80.        , 90.        ],
       [55.        , 65.        , 75.        , 85.        , 95.        ],
       [41.        , 52.        , 63.        , 74.        , 78.        ],
       [78.        , 45.        , 63.        , 47.        , 78.        ],
       [47.        , 56.        , 78.        , 63.        , 87.        ],
       [54.2       , 55.6       , 69.8       , 69.8       , 85.6       ],
       [12.7342059 ,  6.82934843,  6.11228272, 13.55581056,  6.71118469]])

In [22]:
#DataFrames
import pandas as pd
column_labels = ["SDS 2203","SDS 2204","SDS 2205","SDS 2206","SDS 2207"]
row_labels = ["SCT213-C002-001/2025","SCT213-C002-002/2025","SCT213-C002-003/2025","SCT213-C002-004/2025","SCT213-C002-005/2025","Mean"]
marks_df = pd.DataFrame(mean_value_vertical_concat,index=row_labels,columns=column_labels)
marks_df

                      SDS 2203  SDS 2204  SDS 2205  SDS 2206  SDS 2207
SCT213-C002-001/2025      50.0      60.0      70.0      80.0      90.0
SCT213-C002-002/2025      55.0      65.0      75.0      85.0      95.0
SCT213-C002-003/2025      41.0      52.0      63.0      74.0      78.0
SCT213-C002-004/2025      78.0      45.0      63.0      47.0      78.0
SCT213-C002-005/2025      47.0      56.0      78.0      63.0      87.0
Mean                      54.2      55.6      69.8      69.8      85.6

In [10]:
#mean horizontally/row-wise/1 axis
mean_value_horizontal=np.mean(marks,axis=1)
mean_value_horizontal

array([70. , 75. , 61.6, 62.2, 66.2])

In [20]:
#mean horizontally/row-wise/1 axis
mean_value_horizontal=np.mean(marks,axis=1)
mean_value_horizontal
#Reshaping the mean_value_horizontal array to a 2D so as to concatenate
mean_value_horizontal.reshape(5,1)

array([[70. ],
       [75. ],
       [61.6],
       [62.2],
       [66.2]])

In [14]:
std_value_horizontal = np.std(marks,axis=1)
std_value_horizontal

array([14.14213562, 14.14213562, 13.72005831, 14.33038729, 14.52446212])

In [18]:
mean_value_horizontal=np.mean(marks,axis=1)
std_value_horizontal = np.std(marks,axis=1)
mean_value_horizontal_concat=np.concatenate((marks,mean_value_horizontal.reshape(5,1),std_value_horizontal.reshape(5,1)),axis=1)
mean_value_horizontal_concat

array([[50.        , 60.        , 70.        , 80.        , 90.        ,
        70.        , 14.14213562],
       [55.        , 65.        , 75.        , 85.        , 95.        ,
        75.        , 14.14213562],
       [41.        , 52.        , 63.        , 74.        , 78.        ,
        61.6       , 13.72005831],
       [78.        , 45.        , 63.        , 47.        , 78.        ,
        62.2       , 14.33038729],
       [47.        , 56.        , 78.        , 63.        , 87.        ,
        66.2       , 14.52446212]])

In [19]:
mean_value_horizontal_stack = np.hstack((marks,mean_value_horizontal.reshape(5,1),std_value_horizontal.reshape(5,1)))
mean_value_horizontal_stack

array([[50.        , 60.        , 70.        , 80.        , 90.        ,
        70.        , 14.14213562],
       [55.        , 65.        , 75.        , 85.        , 95.        ,
        75.        , 14.14213562],
       [41.        , 52.        , 63.        , 74.        , 78.        ,
        61.6       , 13.72005831],
       [78.        , 45.        , 63.        , 47.        , 78.        ,
        62.2       , 14.33038729],
       [47.        , 56.        , 78.        , 63.        , 87.        ,
        66.2       , 14.52446212]])

In [35]:
#DataFrames
import pandas as pd
column_labels = ["SDS 2203","SDS 2204","SDS 2205","SDS 2206","SDS 2207","Mean","Standard Deviation"]
row_labels = ["SCT213-C002-001/2025","SCT213-C002-002/2025","SCT213-C002-003/2025","SCT213-C002-004/2025","SCT213-C002-005/2025"]
marks_df3 = pd.DataFrame(mean_value_horizontal_stack,index=row_labels,columns=column_labels)
marks_df3

,SDS 2203,SDS 2204,SDS 2205,SDS 2206,SDS 2207,Mean,Standard Deviation
SCT213-C002-001/2025,50.0,60.0,70.0,80.0,90.0,70.0,14.142136
SCT213-C002-002/2025,55.0,65.0,75.0,85.0,95.0,75.0,14.142136
SCT213-C002-003/2025,41.0,52.0,63.0,74.0,78.0,61.6,13.720058
SCT213-C002-004/2025,78.0,45.0,63.0,47.0,78.0,62.2,14.330387
SCT213-C002-005/2025,47.0,56.0,78.0,63.0,87.0,66.2,14.524462

In [36]:
def grading(mean_value_horizontal):
    if mean_value_horizontal>=70 and mean_value_horizontal<=100:
        return 'A'
    
    elif mean_value_horizontal>=60 and mean_value_horizontal<70:
        return'B'
    
    elif mean_value_horizontal>=50 and mean_value_horizontal<60:
        return 'C'
    
    elif mean_value_horizontal>=40 and mean_value_horizontal<50:
        return'D'
    elif mean_value_horizontal>=0 and mean_value_horizontal<40:
        return 'E'
    else:
        return'X'

In [37]:
marks_df3['Grade'] = marks_df3['Mean'].apply(grading)
marks_df3

,SDS 2203,SDS 2204,SDS 2205,SDS 2206,SDS 2207,Mean,Standard Deviation,Grade
SCT213-C002-001/2025,50.0,60.0,70.0,80.0,90.0,70.0,14.142136,A
SCT213-C002-002/2025,55.0,65.0,75.0,85.0,95.0,75.0,14.142136,A
SCT213-C002-003/2025,41.0,52.0,63.0,74.0,78.0,61.6,13.720058,B
SCT213-C002-004/2025,78.0,45.0,63.0,47.0,78.0,62.2,14.330387,B
SCT213-C002-005/2025,47.0,56.0,78.0,63.0,87.0,66.2,14.524462,B

In [17]:
#DataFrames
import pandas as pd
column_labels = ["SDS 2203","SDS 2204","SDS 2205","SDS 2206","SDS 2207","Mean","Standard Deviation"]
row_labels = ["SCT213-C002-001/2025","SCT213-C002-002/2025","SCT213-C002-003/2025","SCT213-C002-004/2025","SCT213-C002-005/2025"]
marks_df = pd.DataFrame(mean_value_horizontal_concat,index=row_labels,columns=column_labels)
marks_df

,SDS 2203,SDS 2204,SDS 2205,SDS 2206,SDS 2207,Mean,Standard Deviation
SCT213-C002-001/2025,50.0,60.0,70.0,80.0,90.0,70.0,14.142136
SCT213-C002-002/2025,55.0,65.0,75.0,85.0,95.0,75.0,14.142136
SCT213-C002-003/2025,41.0,52.0,63.0,74.0,78.0,61.6,13.720058
SCT213-C002-004/2025,78.0,45.0,63.0,47.0,78.0,62.2,14.330387
SCT213-C002-005/2025,47.0,56.0,78.0,63.0,87.0,66.2,14.524462

In [30]:
#mean horizontally/row-wise/1 axis
mean_value_horizontal=np.mean(mean_value_vertical_concat,axis=1)
mean_value_horizontal
#Reshaping the mean_value_horizontal array to a 2D so as to concatenate
mean_value_horizontal.reshape(6,1)

array([[70. ],
       [75. ],
       [61.6],
       [62.2],
       [66.2],
       [67. ]])

In [31]:
mean_value_final_concat=np.concatenate((mean_value_vertical_concat,mean_value_horizontal.reshape(6,1)),axis=1)
mean_value_final_concat

array([[50. , 60. , 70. , 80. , 90. , 70. ],
       [55. , 65. , 75. , 85. , 95. , 75. ],
       [41. , 52. , 63. , 74. , 78. , 61.6],
       [78. , 45. , 63. , 47. , 78. , 62.2],
       [47. , 56. , 78. , 63. , 87. , 66.2],
       [54.2, 55.6, 69.8, 69.8, 85.6, 67. ]])

In [32]:
#DataFrames
import pandas as pd
column_labels = ["SDS 2203","SDS 2204","SDS 2205","SDS 2206","SDS 2207","Mean for Each Subject"]
row_labels = ["SCT213-C002-001/2025","SCT213-C002-002/2025","SCT213-C002-003/2025","SCT213-C002-004/2025","SCT213-C002-005/2025","Mean"]
new_marks_df = pd.DataFrame(mean_value_final_concat,index=row_labels,columns=column_labels)
new_marks_df

,SDS 2203,SDS 2204,SDS 2205,SDS 2206,SDS 2207,Mean for Each Subject
SCT213-C002-001/2025,50.0,60.0,70.0,80.0,90.0,70.0
SCT213-C002-002/2025,55.0,65.0,75.0,85.0,95.0,75.0
SCT213-C002-003/2025,41.0,52.0,63.0,74.0,78.0,61.6
SCT213-C002-004/2025,78.0,45.0,63.0,47.0,78.0,62.2
SCT213-C002-005/2025,47.0,56.0,78.0,63.0,87.0,66.2
Mean,54.2,55.6,69.8,69.8,85.6,67.0